# -*- coding: utf-8 -*-
#  Application Designer: YASH.K
#  Support: yashkamthe2021.it@mmcoe.edu.in
#  PBL - 6
#  13-06-2022
#  1254



from PyQt5 import QtCore, QtGui, QtWidgets
from window2 import Ui_Dialog

class Ui_test(object):
    def openWindow(self):
        self.window = QtWidgets.QDialog()
        self.ui = Ui_Dialog()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, test):
        test.setObjectName("test")
        test.resize(1059, 1085)
        test.setStyleSheet("background-color: rgb(35, 41, 70);\n"
"")
        self.centralwidget = QtWidgets.QWidget(test)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 50, 591, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(35, 41, 70);\n"
"\n"
";color:white\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(300, 100, 441, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 41, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 41, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 41, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 41, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 41, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(158, 89, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 41, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 41, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 41, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 41, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 41, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(158, 89, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 41, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 41, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 41, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 41, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 41, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(158, 89, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.comboBox.setPalette(palette)
        self.comboBox.setAutoFillBackground(False)
        self.comboBox.setStyleSheet("background-color: rgb(35, 41, 70);\n"
"border-color: rgb(255, 255, 255);\n"
"alternate-background-color: rgb(35, 41, 70);\n"
"selection-background-color: rgb(35, 41, 70);\n"
"selection-color: rgb(255, 255, 255);\n"
"\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color:white")
        self.comboBox.setObjectName("comboBox")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 210, 391, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(35, 41, 70);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color:white")
        self.label_2.setText("")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(540, 210, 431, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(35, 41, 70);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color:white")
        self.label_3.setText("")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(180, 160, 251, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(35, 41, 70);\n"
"\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color:white")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(620, 150, 251, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: rgb(35, 41, 70);\n"
"\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: white;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.clicker4())
        self.pushButton.setGeometry(QtCore.QRect(260, 370, 231, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(238, 187, 195);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color:black;\n"
"border-radius:10px\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(800, 720, 161, 61))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color: rgb(35, 41, 70);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color:white")
        self.label_6.setText("")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(780, 470, 181, 61))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: rgb(35, 41, 70);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color:white")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(380, 470, 281, 61))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgb(35, 41, 70);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color:white")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(60, 470, 221, 61))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color: rgb(35, 41, 70);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color:white")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(80, 640, 161, 61))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color: rgb(35, 41, 70);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color:white")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(80, 880, 161, 61))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("background-color: rgb(35, 41, 70);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color:white")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(410, 560, 221, 61))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("background-color: rgb(35, 41, 70);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color:white")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(410, 640, 221, 61))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("background-color: rgb(35, 41, 70);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color:white")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(410, 720, 221, 61))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("background-color: rgb(35, 41, 70);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color:white")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(410, 880, 221, 61))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("background-color: rgb(35, 41, 70);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color:white")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(410, 800, 221, 61))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("background-color: rgb(35, 41, 70);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color:white")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(410, 960, 221, 61))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("background-color: rgb(35, 41, 70);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color:white")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(800, 560, 161, 61))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("background-color: rgb(35, 41, 70);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color:white")
        self.label_18.setText("")
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(800, 640, 161, 61))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("background-color: rgb(35, 41, 70);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color:white")
        self.label_19.setText("")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(800, 800, 161, 61))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("background-color: rgb(35, 41, 70);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color:white")
        self.label_20.setText("")
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(800, 880, 161, 61))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("background-color: rgb(35, 41, 70);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color:white")
        self.label_21.setText("")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(800, 960, 161, 61))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("background-color: rgb(35, 41, 70);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color:white")
        self.label_22.setText("")
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.reset())
        self.pushButton_2.setGeometry(QtCore.QRect(540, 370, 231, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(238, 187, 195);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color:black;\n"
"border-radius:10px")
        self.pushButton_2.setObjectName("pushButton_2")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(190, 280, 211, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 41, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 41, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 41, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 41, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 41, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(158, 89, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 41, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 41, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 41, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 41, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 41, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(158, 89, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 41, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 41, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 41, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 41, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 41, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(158, 89, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.comboBox_2.setPalette(palette)
        self.comboBox_2.setAutoFillBackground(False)
        self.comboBox_2.setStyleSheet("background-color: rgb(35, 41, 70);\n"
"border-color: rgb(255, 255, 255);\n"
"alternate-background-color: rgb(35, 41, 70);\n"
"selection-background-color: rgb(35, 41, 70);\n"
"selection-color: rgb(255, 255, 255);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color:white")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_3.setGeometry(QtCore.QRect(630, 280, 211, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 41, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 41, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 41, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 41, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 41, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(158, 89, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 41, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 41, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 41, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 41, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 41, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(158, 89, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 41, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 41, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 41, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 41, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 41, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(158, 89, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.comboBox_3.setPalette(palette)
        self.comboBox_3.setAutoFillBackground(False)
        self.comboBox_3.setStyleSheet("background-color: rgb(35, 41, 70);\n"
"border-color: rgb(255, 255, 255);\n"
"alternate-background-color: rgb(35, 41, 70);\n"
"selection-background-color: rgb(35, 41, 70);\n"
"selection-color: rgb(255, 255, 255);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color:white")
        self.comboBox_3.setObjectName("comboBox_3")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 550, 321, 241))
        self.tableWidget.setStyleSheet("background-color: transparent;\n"
"border-color: rgb(255, 255, 255);\n"
"color: transparent;\n"
"border : 2px solid white")
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget.setLineWidth(3)
        self.tableWidget.setMidLineWidth(3)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_2.setGeometry(QtCore.QRect(330, 460, 381, 91))
        self.tableWidget_2.setStyleSheet("background-color: transparent;\n"
"border-color: rgb(255, 255, 255);\n"
"color: transparent;\n"
"border : 2px solid white")
        self.tableWidget_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget_2.setLineWidth(3)
        self.tableWidget_2.setMidLineWidth(3)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.tableWidget_3 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_3.setGeometry(QtCore.QRect(10, 460, 321, 91))
        self.tableWidget_3.setStyleSheet("background-color: transparent;\n"
"border-color: rgb(255, 255, 255);\n"
"color: transparent;\n"
"border : 2px solid white")
        self.tableWidget_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget_3.setLineWidth(3)
        self.tableWidget_3.setMidLineWidth(3)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(0)
        self.tableWidget_3.setRowCount(0)
        self.tableWidget_4 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_4.setGeometry(QtCore.QRect(710, 460, 341, 91))
        self.tableWidget_4.setStyleSheet("background-color: transparent;\n"
"border-color: rgb(255, 255, 255);\n"
"color: transparent;\n"
"border : 2px solid white")
        self.tableWidget_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget_4.setLineWidth(3)
        self.tableWidget_4.setMidLineWidth(3)
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(0)
        self.tableWidget_4.setRowCount(0)
        self.tableWidget_5 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_5.setGeometry(QtCore.QRect(330, 550, 381, 81))
        self.tableWidget_5.setStyleSheet("background-color: transparent;\n"
"border-color: rgb(255, 255, 255);\n"
"color: transparent;\n"
"border : 2px solid white")
        self.tableWidget_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget_5.setLineWidth(3)
        self.tableWidget_5.setMidLineWidth(3)
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(0)
        self.tableWidget_5.setRowCount(0)
        self.tableWidget_6 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_6.setGeometry(QtCore.QRect(330, 630, 381, 81))
        self.tableWidget_6.setStyleSheet("background-color: transparent;\n"
"border-color: rgb(255, 255, 255);\n"
"color: transparent;\n"
"border : 2px solid white")
        self.tableWidget_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget_6.setLineWidth(3)
        self.tableWidget_6.setMidLineWidth(3)
        self.tableWidget_6.setObjectName("tableWidget_6")
        self.tableWidget_6.setColumnCount(0)
        self.tableWidget_6.setRowCount(0)
        self.tableWidget_7 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_7.setGeometry(QtCore.QRect(330, 710, 381, 81))
        self.tableWidget_7.setStyleSheet("background-color: transparent;\n"
"border-color: rgb(255, 255, 255);\n"
"color: transparent;\n"
"border : 2px solid white")
        self.tableWidget_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget_7.setLineWidth(3)
        self.tableWidget_7.setMidLineWidth(3)
        self.tableWidget_7.setObjectName("tableWidget_7")
        self.tableWidget_7.setColumnCount(0)
        self.tableWidget_7.setRowCount(0)
        self.tableWidget_8 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_8.setGeometry(QtCore.QRect(10, 790, 321, 241))
        self.tableWidget_8.setStyleSheet("background-color: transparent;\n"
"border-color: rgb(255, 255, 255);\n"
"color: transparent;\n"
"border : 2px solid white")
        self.tableWidget_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget_8.setLineWidth(3)
        self.tableWidget_8.setMidLineWidth(3)
        self.tableWidget_8.setObjectName("tableWidget_8")
        self.tableWidget_8.setColumnCount(0)
        self.tableWidget_8.setRowCount(0)
        self.tableWidget_9 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_9.setGeometry(QtCore.QRect(330, 790, 381, 81))
        self.tableWidget_9.setStyleSheet("background-color: transparent;\n"
"border-color: rgb(255, 255, 255);\n"
"color: transparent;\n"
"border : 2px solid white")
        self.tableWidget_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget_9.setLineWidth(3)
        self.tableWidget_9.setMidLineWidth(3)
        self.tableWidget_9.setObjectName("tableWidget_9")
        self.tableWidget_9.setColumnCount(0)
        self.tableWidget_9.setRowCount(0)
        self.tableWidget_10 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_10.setGeometry(QtCore.QRect(330, 870, 381, 81))
        self.tableWidget_10.setStyleSheet("background-color: transparent;\n"
"border-color: rgb(255, 255, 255);\n"
"color: transparent;\n"
"border : 2px solid white")
        self.tableWidget_10.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget_10.setLineWidth(3)
        self.tableWidget_10.setMidLineWidth(3)
        self.tableWidget_10.setObjectName("tableWidget_10")
        self.tableWidget_10.setColumnCount(0)
        self.tableWidget_10.setRowCount(0)
        self.tableWidget_11 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_11.setGeometry(QtCore.QRect(330, 950, 381, 81))
        self.tableWidget_11.setStyleSheet("background-color: transparent;\n"
"border-color: rgb(255, 255, 255);\n"
"color: transparent;\n"
"border : 2px solid white")
        self.tableWidget_11.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget_11.setLineWidth(3)
        self.tableWidget_11.setMidLineWidth(3)
        self.tableWidget_11.setObjectName("tableWidget_11")
        self.tableWidget_11.setColumnCount(0)
        self.tableWidget_11.setRowCount(0)
        self.tableWidget_12 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_12.setGeometry(QtCore.QRect(710, 550, 341, 81))
        self.tableWidget_12.setStyleSheet("background-color: transparent;\n"
"border-color: rgb(255, 255, 255);\n"
"color: transparent;\n"
"border : 2px solid white")
        self.tableWidget_12.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget_12.setLineWidth(3)
        self.tableWidget_12.setMidLineWidth(3)
        self.tableWidget_12.setObjectName("tableWidget_12")
        self.tableWidget_12.setColumnCount(0)
        self.tableWidget_12.setRowCount(0)
        self.tableWidget_13 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_13.setGeometry(QtCore.QRect(710, 630, 341, 81))
        self.tableWidget_13.setStyleSheet("background-color: transparent;\n"
"border-color: rgb(255, 255, 255);\n"
"color: transparent;\n"
"border : 2px solid white")
        self.tableWidget_13.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget_13.setLineWidth(3)
        self.tableWidget_13.setMidLineWidth(3)
        self.tableWidget_13.setObjectName("tableWidget_13")
        self.tableWidget_13.setColumnCount(0)
        self.tableWidget_13.setRowCount(0)
        self.tableWidget_14 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_14.setGeometry(QtCore.QRect(710, 710, 341, 81))
        self.tableWidget_14.setStyleSheet("background-color: transparent;\n"
"border-color: rgb(255, 255, 255);\n"
"color: transparent;\n"
"border : 2px solid white")
        self.tableWidget_14.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget_14.setLineWidth(3)
        self.tableWidget_14.setMidLineWidth(3)
        self.tableWidget_14.setObjectName("tableWidget_14")
        self.tableWidget_14.setColumnCount(0)
        self.tableWidget_14.setRowCount(0)
        self.tableWidget_15 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_15.setGeometry(QtCore.QRect(710, 790, 341, 81))
        self.tableWidget_15.setStyleSheet("background-color: transparent;\n"
"border-color: rgb(255, 255, 255);\n"
"color: transparent;\n"
"border : 2px solid white")
        self.tableWidget_15.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget_15.setLineWidth(3)
        self.tableWidget_15.setMidLineWidth(3)
        self.tableWidget_15.setObjectName("tableWidget_15")
        self.tableWidget_15.setColumnCount(0)
        self.tableWidget_15.setRowCount(0)
        self.tableWidget_16 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_16.setGeometry(QtCore.QRect(710, 870, 341, 81))
        self.tableWidget_16.setStyleSheet("background-color: transparent;\n"
"border-color: rgb(255, 255, 255);\n"
"color: transparent;\n"
"border : 2px solid white")
        self.tableWidget_16.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget_16.setLineWidth(3)
        self.tableWidget_16.setMidLineWidth(3)
        self.tableWidget_16.setObjectName("tableWidget_16")
        self.tableWidget_16.setColumnCount(0)
        self.tableWidget_16.setRowCount(0)
        self.tableWidget_17 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_17.setGeometry(QtCore.QRect(710, 950, 341, 81))
        self.tableWidget_17.setStyleSheet("background-color: transparent;\n"
"border-color: rgb(255, 255, 255);\n"
"color: transparent;\n"
"border : 2px solid white")
        self.tableWidget_17.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget_17.setLineWidth(3)
        self.tableWidget_17.setMidLineWidth(3)
        self.tableWidget_17.setObjectName("tableWidget_17")
        self.tableWidget_17.setColumnCount(0)
        self.tableWidget_17.setRowCount(0)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.openWindow())
        self.pushButton_3.setGeometry(QtCore.QRect(970, 0, 81, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: rgb(238, 187, 195);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color:black;\n"
"border-radius:10px")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(240, -10, 541, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("background-color: rgb(35, 41, 70);\n"
"\n"
";color:white")
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.tableWidget_8.raise_()
        self.tableWidget_9.raise_()
        self.tableWidget_11.raise_()
        self.tableWidget_6.raise_()
        self.tableWidget_5.raise_()
        self.tableWidget_14.raise_()
        self.tableWidget_15.raise_()
        self.tableWidget_16.raise_()
        self.tableWidget_17.raise_()
        self.tableWidget_13.raise_()
        self.tableWidget_12.raise_()
        self.tableWidget_10.raise_()
        self.tableWidget_7.raise_()
        self.tableWidget.raise_()
        self.tableWidget_4.raise_()
        self.tableWidget_2.raise_()
        self.tableWidget_3.raise_()
        self.label.raise_()
        self.comboBox.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.pushButton.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.label_19.raise_()
        self.label_20.raise_()
        self.label_21.raise_()
        self.label_22.raise_()
        self.pushButton_2.raise_()
        self.comboBox_2.raise_()
        self.comboBox_3.raise_()
        self.pushButton_3.raise_()
        self.label_23.raise_()
        test.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(test)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1059, 26))
        self.menubar.setObjectName("menubar")
        test.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(test)
        self.statusbar.setObjectName("statusbar")
        test.setStatusBar(self.statusbar)

        self.retranslateUi(test)
        QtCore.QMetaObject.connectSlotsByName(test)

#MAKE COMBOBOX CLICKABLE
        self.comboBox.activated.connect(self.clicker)
        self.comboBox_2.activated.connect(self.clicker2)
        self.comboBox_3.activated.connect(self.clicker3)

    def retranslateUi(self, test):
        _translate = QtCore.QCoreApplication.translate
        test.setWindowTitle(_translate("test", "Pedgree Anaylsis"))
        self.label.setText(_translate("test", "Select Disease"))
        self.label_4.setText(_translate("test", "Male"))
        self.label_5.setText(_translate("test", "Female"))
        self.pushButton.setText(_translate("test", "CONFIRM"))
        self.label_7.setText(_translate("test", "Possibilities (%)"))
        self.label_8.setText(_translate("test", "Affected/Carrier/Normal"))
        self.label_9.setText(_translate("test", "Offsprings\' Gender"))
        self.label_10.setText(_translate("test", "BOY"))
        self.label_11.setText(_translate("test", "GIRL"))
        self.label_12.setText(_translate("test", "Affected"))
        self.label_13.setText(_translate("test", "Carrier"))
        self.label_14.setText(_translate("test", "Normal"))
        self.label_15.setText(_translate("test", "Carrier"))
        self.label_16.setText(_translate("test", "Affected"))
        self.label_17.setText(_translate("test", "Normal"))
        self.pushButton_2.setText(_translate("test", "RESET"))
        self.pushButton_3.setText(_translate("test", "INFO"))
        self.label_23.setText(_translate("test", "Pedigree Analysis"))

        diseases=["Porcupine Man","Webbed Toes","Hemophilia","Juvenile retinosctisis","Becker muscular dystrophy","Colorblindness","Red-green colorblindness","Dystrophinopathies","Menkes disease","Fabry disease","Duchenne's muscular dystrophy","Cardiomyopathy","Lesch-Nyhan sydrome"]
        self.comboBox.addItems(diseases)
        autosomal = ["Cystic Fibrosis","Sickle Cell Anemia","Tay-Sach's disease","Gaucher disease","Farber disease","Albinism","Neurofibromatosis","Achondroplasia","Phenylketonuria","Thalassemia"]
        self.comboBox.addItems(autosomal)

        options = ["Carrier", "Affected", "Normal"]
        self.comboBox_2.addItems(options)
        self.comboBox_3.addItems(options)

    def x_link_recessive(self):
        if self.male == "Carrier" and self.female == "Normal":
            self.label_6.setText(f'50 %')
            self.label_21.setText(f'50 %')
        elif self.male == "Normal" and self.female == "Carrier":
            self.label_6.setText(f'25 %')
            self.label_19.setText(f'25 %')
            self.label_21.setText(f'25 %')
            self.label_22.setText(f'25 %')
        elif self.male == "Carrier" and self.female == "Carrier":
            self.label_6.setText(f'25%')
            self.label_22.setText(f'25%')
            self.label_20.setText(f'25%')
            self.label_19.setText(f'25%')
        elif self.male == "Carrier" and self.female =="Affected":
            self.label_20.setText(f'50%')
            self.label_19.setText(f'50%')
        elif self.male == "Normal" and self.female == "Affected":
            self.label_21.setText(f'50%')
            self.label_19.setText(f'50%')
        elif self.male == "Normal" and self.female == "Normal":
            self.label_22.setText(f'50%')
            self.label_6.setText(f'50%')
        elif self.male == "Affected":
            self.label_18.setText(f'NA')
            self.label_19.setText(f'NA')
            self.label_6.setText(f'NA')
            self.label_20.setText(f'NA')
            self.label_21.setText(f'NA')
            self.label_22.setText(f'NA')
            self.label_2.setText(f'Affected Male NOT APPLICABLE')
        else:
            pass

    def x_link_dominant(self):
        if self.male == "Carrier":
            self.label_18.setText(f'NA')
            self.label_19.setText(f'NA')
            self.label_6.setText(f'NA')
            self.label_20.setText(f'NA')
            self.label_21.setText(f'NA')
            self.label_22.setText(f'NA')
            self.label_2.setText(f'Carrier Male NOT APPLICABLE')
        elif self.female == "Carrier":
            self.label_18.setText(f'NA')
            self.label_19.setText(f'NA')
            self.label_6.setText(f'NA')
            self.label_20.setText(f'NA')
            self.label_21.setText(f'NA')
            self.label_22.setText(f'NA')
            self.label_3.setText(f'Carrier Female NOT APPLICABLE')
        elif self.male == "Normal" and self.female == "Normal":
                self.label_22.setText(f'50%')
                self.label_6.setText(f'50%')
        elif self.male == "Normal" and self.female == "Affected":
                #self.label_20.setText(f'50% / 25%')
                #self.label_18.setText(f'50% / 25%')
                pass
        elif self.male == "Affected" and self.female == "Affected":
                pass
        elif self.male == "Affected" and self.female == "Normal":
                self.label_20.setText(f'50%')
                self.label_6.setText(f'50%')
        else:
                pass
        
    def y_link(self):
        if self.male == "Affected" and self.female == "Normal":
                self.label_22.setText(f'50%')
                self.label_18.setText(f'50%')
        elif self.male == "Normal":
            self.label_18.setText(f'NA')
            self.label_19.setText(f'NA')
            self.label_6.setText(f'99%')
            self.label_20.setText(f'NA')
            self.label_21.setText(f'NA')
            self.label_22.setText(f'99%')
            self.label_2.setText(f'Normal Male NOT APPLICABLE')
        elif self.male == "Carrier":
            self.label_18.setText(f'NA')
            self.label_19.setText(f'NA')
            self.label_6.setText(f'NA')
            self.label_20.setText(f'NA')
            self.label_21.setText(f'NA')
            self.label_22.setText(f'NA')
            self.label_2.setText(f'Carrier Male NOT APPLICABLE')
        elif self.male == "Affected":
            self.label_18.setText(f'NA')
            self.label_19.setText(f'NA')
            self.label_6.setText(f'NA')
            self.label_20.setText(f'NA')
            self.label_21.setText(f'NA')
            self.label_22.setText(f'NA')
            self.label_2.setText(f'Affected Male NOT APPLICABLE')
        else:
                pass

    def autosomal_recessive(self):
        self.label_9.setText(f'')
        self.label_10.setText(f'')
        self.label_11.setText(f'')
        self.label_15.setText(f'')
        self.label_16.setText(f'')
        self.label_17.setText(f'')
        if self.male == "Normal" and self.female == "Normal":
                self.label_6.setText(f'99%')
        elif self.male == "Normal" and self.female == "Affected":
                self.label_19.setText(f'99%')
        elif self.male == "Normal" and self.female == "Carrier":
                self.label_6.setText(f'50%')
                self.label_19.setText(f'50%')
        elif self.male == "Affected" and self.female == "Normal":
                self.label_19.setText(f'99%')
        elif self.male == "Carrier" and self.female == "Normal":
                self.label_19.setText(f'50%')
                self.label_6.setText(f'50%')
        elif self.male == "Carrier" and self.female == "Carrier":
                self.label_19.setText(f'50%')
                self.label_6.setText(f'25%')
                self.label_18.setText(f'25%')
        elif self.male == "Affected" and self.female == "Carrier":
                self.label_18.setText(f'50%')
                self.label_19.setText(f'50%')
        elif self.male == "Carrier" and self.female == "Affected":
                self.label_18.setText(f'50%')
                self.label_19.setText(f'50%')
        elif self.male == "Affected" and self.female == "Affected":
                self.label_18.setText(f'99%')


    def clicker(self):
        self.label.setText(f'You Selected: {self.comboBox.currentText()}')
        self.disease = self.comboBox.currentText()
        print(self.disease)

    def clicker2(self):
        self.label_2.setText(f'You Selected: {self.comboBox_2.currentText()}')
        self.male = self.comboBox_2.currentText()

    def clicker3(self):
        self.label_3.setText(f'You Selected: {self.comboBox_3.currentText()}')
        self.female = self.comboBox_3.currentText()

    def clicker4(self):
        if self.disease == "Hemophilia":
            self.x_link_recessive()
        elif self.disease == "Juvenile retinosctisis":
            self.x_link_recessive()
        elif self.disease == "Becker muscular dystrophy":
            self.x_link_recessive()
        elif self.disease == "Colorblindness":
            self.x_link_recessive()
        elif self.disease == "Red-green colorblindness":
            self.x_link_recessive()
        elif self.disease == "Dystrophinopathies":
            self.x_link_recessive()
        elif self.disease == "Menkes disease":
            self.x_link_recessive()
        elif self.disease == "Fabry disease":
            self.x_link_recessive()
        elif self.disease == "Duchenne's muscular dystrophy":
            self.x_link_recessive()
        elif self.disease == "cardiomyopathy":
            self.x_link_recessive()
        elif self.disease == "Lesch-Nyhan sydrome":
            self.x_link_recessive()
        elif self.disease == "Porcupine Man":
                self.y_link()
        elif self.disease == "Webbed Toes":
                self.y_link()
        elif self.disease == "Cystic Fibrosis":
                self.autosomal_recessive()
        elif self.disease == "Sickle Cell Anemia":
                self.autosomal_recessive()
        elif self.disease == "Tay-Sach's disease":
                self.autosomal_recessive()
        elif self.disease == "Gaucher disease":
                self.autosomal_recessive()
        elif self.disease == "Farber disease":
                self.autosomal_recessive()
        elif self.disease == "Albinism":
                self.autosomal_recessive()
        elif self.disease == "Neurofibromatosis":
                self.autosomal_recessive()
        elif self.disease == "Achondroplasia":
                self.autosomal_recessive()
        elif self.disease == "Phenylketonuria":
                self.autosomal_recessive()
        elif self.disease == "Thalassemia":
                self.autosomal_recessive()
        

        else:
            exit()

    def reset(self):
        self.label_9.setText(f"Offsprings' Gender")
        self.label_10.setText(f'BOY')
        self.label_11.setText(f'GIRL')
        self.label_15.setText(f'Carrier')
        self.label_16.setText(f'Affected')
        self.label_17.setText(f'Normal')
        self.label_19.setText(f'')
        self.label_18.setText(f'')
        self.label_6.setText(f'')
        self.label_20.setText(f'')
        self.label_21.setText(f'')
        self.label_22.setText(f'')
        self.label_3.setText(f'')
        self.label_2.setText(f'')
        self.label.setText(f'Select Disease')


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    test = QtWidgets.QMainWindow()
    ui = Ui_test()
    ui.setupUi(test)
    test.show()
    sys.exit(app.exec_())
